error_reporting = E_ALL
display_errors = On
display_startup_errors = On
log_errors = On
memory_limit = 256M
upload_max_filesize = 64M
post_max_size = 64M
date.timezone = UTC

# APCu Configuration
apc.enabled = 1
apc.enable_cli = 1
apc.shm_size = 64M
