<?php

declare(strict_types=1);

use Core\View;

$title = View::escape($title ?? 'About LilaPHP');
$csrfField = $csrf_input ?? '';

echo View::html(function () use ($title, $csrfField) {
    return <<<HTML
<div style="max-width: 800px; margin: 0 auto; padding: 2rem 0;">
    <div style="margin-bottom: 2rem;">
        <a href="/" style="color: #38bdf8; text-decoration: none; font-size: 0.95rem;">&larr; Back to Home</a>
    </div>

    <h1 style="font-size: 2.5rem; font-weight: 700; margin-bottom: 1rem; color: #f8fafc;">
        {$title}
    </h1>

    <p style="font-size: 1.15rem; color: #94a3b8; line-height: 1.7; margin-bottom: 2rem;">
        LilaPHP is engineered for microsecond-level response times, zero external runtime dependencies, and maximum developer ergonomics.
    </p>

    <div style="background: #1e293b; border: 1px solid #334155; border-radius: 8px; padding: 2rem; margin-bottom: 2rem;">
        <h2 style="color: #38bdf8; margin-top: 0; margin-bottom: 1rem; font-size: 1.5rem;">Core Architecture Principles</h2>
        <ul style="color: #cbd5e1; line-height: 1.8; padding-left: 1.25rem;">
            <li><strong>Decoupled Web & API:</strong> Static assets served at line speed from <code>public/</code>, view routes in <code>app/routes/</code>, and JSON REST routes in <code>app/routes/api/</code>.</li>
            <li><strong>Auto 405 Method Handling:</strong> When an endpoint does not match the HTTP verb, a standardized 405 Method Not Allowed is emitted automatically.</li>
            <li><strong>Tiered Caching:</strong> Multi-layer caching hierarchy prioritizing APCu RAM, Redis cluster, and persistent file caching.</li>
            <li><strong>CSRF & Security:</strong> Built-in AES-256 encryption, rate limiting, and automatic CSRF tokens passed to view scopes.</li>
            <li><strong>Zero Bloat:</strong> Full functionality with native PHP 8.4+ standard library constructs.</li>
        </ul>
    </div>

    <div style="background: #1e293b; border: 1px solid #334155; border-radius: 8px; padding: 1.5rem;">
        <h3 style="color: #38bdf8; margin-top: 0; margin-bottom: 0.5rem; font-size: 1.2rem;">CSRF Security Demo</h3>
        <p style="color: #94a3b8; font-size: 0.95rem; margin-bottom: 1rem;">The hidden input below is automatically generated by LilaPHP with the session CSRF token:</p>
        <div style="background: #0f172a; padding: 0.75rem 1rem; border-radius: 6px; font-family: monospace; font-size: 0.85rem; color: #a5f3fc; overflow-x: auto;">
            {$csrfField}
        </div>
    </div>
</div>
HTML;
});
